backend:
  name: github
  repo: ava1313/Travel-Blog  # Replace with your GitHub username and repository name
  base_url: http://avagianos.ddns.net  # Replace with your Raspberry Pi's external URL
  auth_endpoint: oauth-callback.php  # Replace with your OAuth callback PHP script

media_folder: "img/uploads"
public_folder: "/img/uploads"
collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts"
    create: true
    fields:
      - { name: "title", label: "Title", type: "string" }
      - { name: "body", label: "Body", type: "markdown" }
